;-------------------------------------------------------------------------
;
; BeebLink - BBC Micro file storage system
; Copyright (C) 2019 Tom Seddon
; 
; This program is free software: you can redistribute it and/or
; modify it under the terms of the GNU General Public License as
; published by the Free Software Foundation, either version 3 of the
; License, or (at your option) any later version.
; 
; This program is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
; General Public License for more details.
; 
; You should have received a copy of the GNU General Public License
; along with this program. If not, see
; <https://www.gnu.org/licenses/>.
;
;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

upurs: .block
                
;-------------------------------------------------------------------------

prepare: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

unprepare: .proc
                .pend


;-------------------------------------------------------------------------

begin_recv: .proc
                rts
                .pend

;-------------------------------------------------------------------------

begin_send: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

send_header_byte: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

send_payload_byte: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

recv_header_byte: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

recv_payload_byte: .proc
                rts
                .pend

;-------------------------------------------------------------------------

startup: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

status_text: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

                .bend

;-------------------------------------------------------------------------

                .send code

;-------------------------------------------------------------------------
;-------------------------------------------------------------------------

link_name='UPURS'
link_subtype=SERIAL_SUBTYPE_UPURS

link_prepare=upurs.prepare
link_unprepare=upurs.unprepare

link_begin_recv=upurs.begin_recv
link_begin_send=upurs.begin_send

link_send_header_byte=upurs.send_header_byte
link_send_payload_byte=upurs.send_payload_byte
link_recv_header_byte=upurs.recv_header_byte
link_recv_payload_byte=upurs.recv_payload_byte
                
link_startup=upurs.startup
link_status_text=upurs.status_text
                
; link_send_file_data_parasite=upurs.send_file_data_parasite

; link_send_file_data_host=upurs.send_file_data_host

; link_recv_file_data_parasite=upurs.recv_file_data_parasite

; link_recv_file_data_host=upurs.recv_file_data_host
