name: Build BeebLink

on:
  push:
    branches:
      - wip/tom

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make -f tools/Makefile.ci.mak github_ci_windows

  build-macos-intel:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make -f tools/Makefile.ci.mak github_ci_macos_intel

  build-macos-arm:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make -f tools/Makefile.ci.mak github_ci_macos_arm
