name: Build BeebLink

on:
  push:
    branches:
      - wip/tom

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: cmd /c beeb\make.bat -C tools/ci github_ci_windows VERBOSE=1 INSTALL_PREREQUISITES=1 NAME_SUFFIX=-windows

  build-macos-intel:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make -C tools/ci github_ci_macos_intel VERBOSE=1 INSTALL_PREREQUISITES=1 NAME_SUFFIX=-macos-intel

  build-macos-arm:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make -C tools/ci github_ci_macos_arm VERBOSE=1 INSTALL_PREREQUISITES=1 NAME_SUFFIX=-macos-applesilicon
